Squashed commit of the following:
commit d0bc78fed792f20b56f2c0a231d96584656ff867
Author: Alexander Mnich <alex@mnich.dev>
Date:   Sat Dec 20 16:16:03 2025 +0100

    feat: add new test workflow

commit dc32c1597f8039236e2c92ce963a66aa3c2c9589
Author: Alexander Mnich <alex@mnich.dev>
Date:   Sat Dec 20 10:57:45 2025 +0100

    chore: rename validation script

commit 38ce0dea22391e86b42add10a04fa52930f7e389
Author: Alexander Mnich <alex@mnich.dev>
Date:   Sat Dec 20 10:57:01 2025 +0100

    fix: fix wait for finished validation

commit c6e05404a4ffccfd5196f3994013da5582cd2b37
Author: Alexander Mnich <alex@mnich.dev>
Date:   Fri Dec 19 22:32:16 2025 +0100

    feat: init test file

commit 2be45c3552a44b1091365ff5a936db260d126446
Author: Alexander Mnich <alex@mnich.dev>
Date:   Fri Dec 19 21:39:15 2025 +0100

    feat: allow sandbox script without manifest url

commit 809e264375d87cd5fff8543913319f962c8380f3
Author: Alexander Mnich <alex@mnich.dev>
Date:   Fri Dec 19 21:30:01 2025 +0100

    chore: rename testing folder

commit fef43401f47c21156dffa5f0e411a5af5298ecf8
Author: Alexander Mnich <alex@mnich.dev>
Date:   Fri Dec 19 21:26:48 2025 +0100

    chore: cleanup repo

commit 3751401e677a380895779a11a44968ee9471776d
Author: Alexander Mnich <alex@mnich.dev>
Date:   Sun Jun 29 11:07:58 2025 +0200

    update sandbox tests

diff --git a/.github/workflows/test-manifest-selfhosted.yml b/.github/workflows/test-manifest-selfhosted.yml
--- a/.github/workflows/test-manifest-selfhosted.yml
+++ b/.github/workflows/test-manifest-selfhosted.yml
@@ -45,5 +45,46 @@ jobs:
         shell: powershell
         env:
           TIMEOUT: ${{ inputs.Timeout }}
-        run: .\scripts\testing\Test-Manifest-Host.ps1 -ManifestURL ${{ env.manifesturl }}
+        run: .\scripts\validation\Test-Manifest-Host.ps1 -ManifestURL ${{ env.manifesturl }}
         #continue-on-error: true
+
+      - name: Take screenshot using FFmpeg
+        if: always()
+        shell: powershell
+        run: |
+          #start ms-settings:appsfeatures
+
+          # Wait for the settings app to open
+          Start-Sleep -Seconds 5
+
+          $ffmpegExe = where.exe ffmpeg
+          if (-not $ffmpegExe) {
+            $ffmpegExe = where.exe ffmpeg.exe
+          }
+          
+          # Use FFmpeg to capture screen
+          Write-Host "Capturing screenshot with FFmpeg..."
+          & $ffmpegExe -f gdigrab -framerate 1 -i desktop -frames:v 1 screenshot.png
+
+          # Verify screenshot was created
+          if (Test-Path "screenshot.png") {
+            Write-Host "Screenshot captured successfully"
+          } else {
+            Write-Error "Screenshot capture failed"
+            exit 1
+          }
+
+      - name: Upload Screenshot Artifact
+        if: always()
+        uses: actions/upload-artifact@v4
+        with:
+          #name: screenshot-${{ env.date }}-${{ env.manifestname }}
+          name: screenshot-${{ env.date }}
+          path: screenshot.png 
+          retention-days: 30  # Artifacts will be kept for 30 days
+
+      - name: Check if Test Script Failed
+        if: steps.test.conclusion == 'failure' #failure()  # This runs only if the previous step failed
+        run: |
+          echo "Test Script failed. Marking workflow as failed."
+          exit 1
